### ISSUE TITLE
[Bug] 2.4Ghz dongle incompatible with KVMs

### ISSUE THREAD

**Issue by justMaku** [Keychron/qmk_firmware#391]
### Describe the Bug

I just got my Keychron Q1 Max (ANSI + Knob) and I'm in love with this keyboard, unfortunately there seems to be one issue that's giving me troubles is the KVM port switching through a key-combo on my [Level1Techs KVM](https://www.store.level1techs.com/products/p/combo-displayport-usb-c-kvm-with-usb-power-delivery)

This KVM supports port-switching through key-chords (by tapping left control twice and then a number of the port, i.e ctrl,ctrl,1 would switch to port 1). This feature seems to require the keyboard HID reports/descriptors to be [defined in a specific way](https://forum.level1techs.com/t/no-kvm-port-switching-on-keychron-q1-max-over-2-4ghz-receiver/232007).

It works fine with direct USB connection, but when using the dongle, the KVM seems to not detect the key-presses properly.

I have [another keyboard](https://www.whatgeek.com/products/skn-bluebird75-tri-mode-wireless-mechanical-keyboard?_pos=1&_sid=a39661741&_ss=r) that while not marketed as Keychron seems to be actually manufactured by Keychron and uses similar firmware/dongle. That keyboard works just fine with the KVM both wired and wireless, so I assume the Q1 Max dongle firmware is doing something a bit differently. 

@lokher - any chance you have knowledge of what's going on here? I have tried the 0.2.3, 0.2.4 and 0.3.0 firmware for the dongle to no avail. 

### Keyboard Used

Keychron Q1 Max 

### Operating System

macOS

### qmk doctor Output

```text

```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by PeterMortensen** [comment]
It is likely due to the (full) [NKRO](https://en.wikipedia.org/wiki/Key_rollover) (it was ***forced*** with the [early 2025 Keychron keyboard main firmware updates](https://www.reddit.com/r/Keychron/comments/1j092s2/comment/ml0wljn/)).

Try a firmware version from before January 2025. It defaults to [6KRO](https://en.wikipedia.org/wiki/Key_rollover). At least identify (full) NKRO as the cause of the problem. Compile from source, or use [the one on GitHub](https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/q1_max/firmware) (it is still the old version; save a copy of it while you still can. With [one opened](https://github.com/Keychron/qmk_firmware/blob/wireless_playground/keyboards/keychron/q1_max/firmware/keychron_q1_max_iso_encoder_via.bin), use the tilted hamburger menu in the upper right (hover text *"More file actions"*) &rarr; *Download*). 

You can also confirm it by using (full) NKRO with the other keyboard, presuming it has such an option. It should work equally bad. Even if it is not documented, if they have ripped off QMK (it says *"[Via](https://docs.keeb.io/via) key change"*), toggle with ***Fn*** + ***N*** might work. In any case, you should be able map it to a key, e.g., ***Fn*** + ***N***, by using keycode "`MAGIC_TOGGLE_NKRO`" (***KEYMAP*** &rarr; ***SPECIAL*** &rarr; ***Any*** in Via (the very last one in the list, with hover text *"Enter any QMK keycode"*)). Via seems to accept "`MAGIC_TOGGLE_NKRO`" (in this case, the full keycode; unlike what is usually the case, it doesn't accept the alias, "`NK_TOGG`")

Here is [a simple test](https://www.reddit.com/r/Keychron/comments/198jmqn/comment/lb1dbof/) to positively know which RO mode the keyboard is in (do it in wired mode!).

### An alternative reason

You use older firmware, but you have accidentally put the keyboard into (full) NKRO mode. Toggle back to 6KRO with ***Fn*** + ***N*** (the nuclear option is to [reset to factory defaults](https://www.reddit.com/r/Keychron/comments/1fi6z0o/comment/lnfddp3/)).

### References

 * [Q1 Max default keymap](https://github.com/Keychron/qmk_firmware/blob/wireless_playground/keyboards/keychron/q1_max/iso_encoder/keymaps/via/keymap.c#L58). For RGB control, [HSV](https://en.wikipedia.org/wiki/HSL_and_HSV) is used: "HU" = "[hue](https://en.wikipedia.org/wiki/Hue)" (colour) = "H". "SA" = [saturation](https://en.wikipedia.org/wiki/Colorfulness#Saturation) = "S". "VA" = "[value](https://en.wikipedia.org/wiki/Brightness)" (brightness) = "V". "I" = increase. "D" = decrease. Example: keycode `RGB_SAD` is for ***decreasing*** (`D`) the ***saturation*** (`SA`) (the `SAD` part (no pun intended)). "`MOD`" is for changing RGB lighting mode (23 different ones expected). For example,  "`NK_TOGG`" (an alias of "`QK_MAGIC_TOGGLE_NKRO`") for toggling between 6KRO and (full) NKRO
 * [Q1 Max source code](https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/q1_max). Note: In [Keychron's fork](https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron) and in that fork, in [Git](https://en.wikipedia.org/wiki/Git)&nbsp;branch ***"wireless_playground"*** (not the default&nbsp;branch). Note that the base installation (and usage) has [become much more complicated on Linux](https://www.reddit.com/r/Keychron/comments/1cxnqtu/comment/m80aes2/). No matter the Git&nbsp;branch, for example, ***"wireless_playground"***, it requires [special setup of QMK](https://www.reddit.com/r/Keychron/comments/1cxnqtu/comment/l55cx8r/) (the standard QMK instructions and many other guides will ***not*** work (because they implicitly assume the main QMK&nbsp;repository and a particular Git branch)). [Source&nbsp;code&nbsp;commits](https://github.com/Keychron/qmk_firmware/commits/wireless_playground/) ([RSS&nbsp;feed](https://github.com/Keychron/qmk_firmware/commits/wireless_playground.atom). Latest:&nbsp;2025-05-30).
 * Documentation for [the new keycodes](https://github.com/qmk/qmk_firmware/blob/master/docs/keycodes.md) (main QMK repository)
 * Documentation for [the old keycodes](https://github.com/Keychron/qmk_firmware/blob/wireless_playground/docs/keycodes.md) (though even older ones may exist). For example, used by some [Git](https://en.wikipedia.org/wiki/Git) branches in [Keychron's fork](https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/k10_pro)
 * Documentation for [the old keycodes](https://github.com/samhocevar-forks/qmk-firmware/blob/master/docs/keycodes.md) from 2019. In general, these are the ones accepted by [Via](https://docs.keeb.io/via) and possibly the [Via clone](https://www.reddit.com/r/Keychron/comments/1buwibx/comment/kxx3kt0/) (in most cases only an alias and only one of the aliases if there is more than one).

**Comment by justMaku** [comment]
I did compile the firmware from `wls_2025q1` with both `NKRO_ENABLE` and `APDAPTIVE_NKRO_ENABLE` set to 0 and while the keyboard did enter the 6KRO mode, it still didn't work.

**Comment by PeterMortensen** [comment]
It might be due to [the number of USB endpoints](https://www.reddit.com/r/Keychron/comments/xxpos3/psa_disabling_mouskey_and_nkro_in_firmware_fixed/), then.

**Comment by PeterMortensen** [comment]
There is also the issue of the Bluetooth part [affecting the](https://www.reddit.com/r/Keychron/comments/1ihh33r/comment/maxll5p/) '2.4&nbsp;[GHz](https://en.wikipedia.org/wiki/Hertz#SI_multiples)' part:

 1. When RGB light is ***off*** (in at least one wireless mode)
 2. Mouse actions in '2.4&nbsp;[GHz](https://en.wikipedia.org/wiki/Hertz#SI_multiples)' mode
 3. ***Intermittent*** swapping of Cmd/Opt in Mac mode (in at least one wireless mode)
 4. Possibly other yet undiscovered things 

They (at least the known ones) are fixed by updating the Bluetooth firmware version, for example, to [0.2.1](https://www.reddit.com/r/Keychron/comments/1as61bs/comment/kswoy5c/) (though it [may also be detrimental](https://www.reddit.com/r/Keychron/comments/1g1698j/comment/m14b9bc/); it can be reverted using [the links here](https://www.reddit.com/r/Keychron/comments/1as61bs/comment/kswoy5c/)).

I don't know if it affects this problem, but I wouldn't be surprised if it did.

At least it ought to be excluded as the cause (or not).

***Note***: [Don't brick](https://www.reddit.com/r/Keychron/comments/1h33l08/comment/lzozkuo/) the Bluetooth module!!!! For example, by flashing the wrong firmware. Double and triple check.

**Comment by justMaku** [comment]
Compiled firmware with Mouse Key support off, still not working.

**Comment by PeterMortensen** [comment]
How do you *positively* know the feature(s) has been disabled? (Not a rhetorical question.)

**Comment by justMaku** [comment]
I have compared the USB descriptors using usbhid_dump and also by purposely making the code behind `#ifdef NKRO_ENABLE` invalid, to make sure my configuration option is being applied and the code is not being compiled.

I believe this is must be related to either the dongle or the wireless firmware, because this **work just fine** on stock firmware with direct wired connection.

I spoke with @lokher directly and he is looking into it.

**Comment by justMaku** [comment]
Okay, can confirm that removing the removing MOUSEKEY_ENABLE from my config actually fixed my issue! I've must have forgot to reset back to 2.4ghz while testing previously.

Thank you @PeterMortensen!

**Comment by justMaku** [comment]
Well, I tried flashing NKRO-capable (but without MOUSEKEY_ENABLE) and it stopped working. Reverted back to the NKRO disabled and mousekey disabled, and it also doesn't work… Something is off.

**Comment by PeterMortensen** [comment]
How is it set? In a JSON file? It may be necessary to run 'qmk clean'.

I change the USB version number in file *[info.json](https://github.com/Keychron/qmk_firmware/blob/wireless_playground/keyboards/keychron/v6_max/iso_encoder/info.json)* (field "device_version") in order to check that a change actually makes it onto the keyboard, and I have to run 'qmk clean' for the new value to be used (though I don't know if it is still necessary).

I read it out with (on Linux):

    lsusb -v -d3434:0961 2>/dev/null | grep bcdDevice # V6 Max-specific

Sample output (for "2.8.0" in the JSON file):

    bcdDevice            2.80

**Comment by PeterMortensen** [comment]
How is it set? In a JSON file? It may be necessary to run 'qmk clean' (or the equivalent).

Though MOUSEKEY_ENABLE would suggest it is in file *rules.mk*. Otherwise, I think it is supposed to be in file *[info.json](https://github.com/Keychron/qmk_firmware/blob/wireless_playground/keyboards/keychron/q1_max/info.json#L14)*:

    "mousekey" : true,

That is presuming it is actually used (not ignored). It is [the same](https://github.com/Keychron/qmk_firmware/blob/wls_2025q1/keyboards/keychron/q1_max/info.json#L14) in branch ***"wls_2025q1"****.

I *think* setting it in file *rules.mk* will override any setting in file *info.json*, so it is probably OK.

I change the USB version number in the other file *[info.json](https://github.com/Keychron/qmk_firmware/blob/wireless_playground/keyboards/keychron/v6_max/iso_encoder/info.json#L4)* (field "device_version") in order to check that a change to the source code actually makes it onto the keyboard, and I have to run 'qmk clean' for the new value to be used (or had&mdash;I don't know if it is still necessary). The file was later renamed to *[keyboard.json](https://github.com/Keychron/qmk_firmware/blob/wls_2025q1/keyboards/keychron/q1_max/iso_encoder/keyboard.json)*.

After flashing, I read the version number out with (on Linux):

    lsusb -v -d3434:0961 2>/dev/null | grep bcdDevice # V6 Max-specific

Sample output (for "2.8.0" in the JSON file):

    bcdDevice            2.80

**Comment by justMaku** [comment]
Okay, I finally got it to work reliably - after flashing a firmware with `MOUSEKEY_ENABLE`, `NKRO_ENABLE` and `APDAPTIVE_NKRO_ENABLE` disabled, you also have to do "FN+N" to disable NKRO once again (for some bizarre reason).

**Comment by PeterMortensen** [comment]
Re *"you also have to do "FN+N" to disable NKRO once again"*. This could be consistent with [`FORCE_NKRO`](https://github.com/qmk/qmk_firmware/blob/master/docs/getting_started_make_guide.md) enabled (not a default value, but forced at every keyboard startup).

The [early 2025 Keychron keyboard main firmware updates](https://www.reddit.com/r/Keychron/comments/1j092s2/comment/ml0wljn/) ([now represented](https://github.com/Keychron/qmk_firmware/issues/217#issuecomment-2937073410) in branch ***"[wireless_playground](https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/v6_max)"***) forces NKRO (it is not even possible to revert to 6KRO), so maybe there is some kind of cross-pollination? Here is [a&nbsp;confirmed&nbsp;case](https://www.reddit.com/r/Keychron/comments/1jzedhj/comment/mn665g3/) of problems with KVMs for that firmware.

I haven't checked the source code to see if that is actually the case.

Also note: It [has been deprecated](https://docs.qmk.fm/ChangeLog/20250525#deprecation-of-usb-force-nkro-force-nkro-25262) in the main QMK project ([numero 25262](https://github.com/qmk/qmk_firmware/pull/25262)), but presumably it was after the effective date for branch *"[wls_2025q1](https://github.com/Keychron/qmk_firmware/tree/wls_2025q1/keyboards/keychron/k10_version_2)"*:

> *"forcing of NKRO on every boot has been deprecated... The deprecated options will be removed in a future breaking changes cycle."*

**Comment by PeterMortensen** [comment]
(Very slightly related: In the ***"[wls_2025q1](https://www.reddit.com/r/Keychron/comments/1j092s2/comment/mvu2xyk/)"*** branch, trying to disable NKRO (in order to be able to ***enable debugging output***) [results in a compile error](https://github.com/Keychron/qmk_firmware/issues/395), at least for [a K10 V2](https://github.com/Keychron/qmk_firmware/issues/386#issuecomment-2956304666):

> *'kb_report_changed' undeclared*

)

**Comment by justMaku** [comment]
You need to disable `APDAPTIVE_NKRO_ENABLE` too.

**Comment by PeterMortensen** [comment]
Thanks. [Adding the line](https://github.com/Keychron/qmk_firmware/issues/395#issuecomment-3046373929)

    #undef APDAPTIVE_NKRO_ENABLE

in file *[config.h](https://github.com/Keychron/qmk_firmware/blob/wls_2025q1/keyboards/keychron/k10_version_2/iso/rgb/config.h#L44)* made that compile error go away. 

And [disabling three QMK features](https://github.com/Keychron/qmk_firmware/issues/395#issuecomment-3046373929) allowed debug output to be enabled. It worked as expected after building and flashing. Debug output was captured with *[hid_listen](https://pmortensen.eu/world2/2023/09/11/qmk-debugging-blues-on-ubuntu/)*.
